create table member
(
    UUID bigint generated by default as identity,
    member_id varchar(50) not null,
    PASSWORD varchar(50) not null,
    member_name varchar(10),
    primary key (UUID),
    unique (member_id)
);

create table board
(
    boardNum bigint generated by default as identity,
    boardTitle varchar(50) not null,
    memberId varchar(50) not null,
    writer varchar(10) not null,
    boardDate date not null,
    content varchar(100) not null,
    primary key (boardNum),
    foreign key (memberId) references member(member_id)
);

create table file
(
    boardNum bigint not null,
    fileId bigint generated by default as identity,
    uploadFileName varchar(50) not null,
    storeFileName varchar(50) not null,
    primary key (fileId),
    foreign key (boardNum) references board(boardNum)
);

create table rewrite
(
    reId bigint generated by default as identity,
    memberId varchar(50) not null,
    reContent varchar(200) not null,
    reWriter varchar(10) not null,
    reDate date not null,
    boardNum bigint not null,
    primary key (reId),
    foreign key (memberId) references member(member_id),
    foreign key (boardNum) references board(boardNum)
);